services:

  gateway:
      build:
        context: ./gateway
      ports:
        - "3000:3000"
      depends_on:
        - catalogue
        - commande
        - utilisateur

  catalogue:
    build:
      context: ./catalogue
    ports:
      - "8081:8081"
    networks:
      - microservices-network

  commande:
    build:
      context: ./commande
    ports:
      - "8082:8082"

  utilisateur:
    build:
      context: ./utilisateur
    ports:
      - "8083:8083"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
