services:
  catalogue:
    build:
      context: ./catalogue
    ports:
      - "8081:8081"
    networks:
      - microservices-network

  utilisateur:
    build:
      context: ./utilisateur
    ports:
      - "8083:8083"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
