version: "3.9"

services:
  users:
    build:
      context: .
    ports:
      - "8083:8083"
    networks:
      - users-network
    container_name: users-service

networks:
  users-network:
    driver: bridge
